# Array Processing with NumPy
Some of the exercises are taken from https://pynative.com/python-numpy-exercise/.

In [1]:
import numpy as np

## Create an Array
Write a Python program that creates an integer array with 4 elements of type unsigned int16 and prints the shape, the number of dimensions, and the length of each element (in bytes).

In [6]:
a = np.empty(shape=(4), dtype=np.int16)
a.shape, a.ndim, a.itemsize

((4,), 1, 2)

## Create a 2D Array
Write a Python program that creates a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [7]:
a = np.arange(100, 200, 10).reshape((5, 2))
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

## Select Rows and Columns
Write a Python program to return the array of odd rows and even columns from the given numpy array.

In [8]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [11]:
a[1::2, ::2]

array([[15, 21],
       [39, 45]])

## Compute Numerical Operations
Write a Python program that computes the sum, the element-wise multiplication, and the matrix multiplication of the given numpy arrays. 

In [12]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])
a, b

(array([[ 5,  6],
        [21, 18]]),
 array([[15, 33],
        [ 4,  7]]))

In [16]:
a + b
a * b
a.dot(b)

array([[ 99, 207],
       [387, 819]])

## Sort by Rows and Columns
Write a Python program to sort the given 2D array in 2 scenarios: (1) Sort it by the second row; (2) Sort it by the second column.  

In [20]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
a

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [21]:
a.sort(axis=1)
a

array([[34, 43, 73],
       [12, 22, 82],
       [53, 66, 94]])

## Split and Concatenate an Array
Write a Python program to split the given 8x3 array into 4 equal-sized sub-arrays. Then, concatenate the splitted arrays to rebuilt the original array.

In [22]:
a = np.arange(10, 34, 1).reshape(8, 3)
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [28]:
x1, x2, x3, x4 = np.vsplit(a, 4)
np.vstack([x1, x2, x3, x4])

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

## Delete and Insert Columns
Write a Python Program that deletes the second column from the given array and insert the given new column in its place.

In [29]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]) 
new_column = np.array([[10, 10, 10]])
a, new_column

(array([[34, 43, 73],
        [82, 22, 12],
        [53, 94, 66]]),
 array([[10, 10, 10]]))

In [30]:
a[:, 1] = new_column
a

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])